"""Add repost_id to posts

Revision ID: 92871ebea8b3
Revises: 13c26f223e21
Create Date: 2026-07-06 15:18:36.324129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92871ebea8b3'
down_revision: Union[str, None] = '13c26f223e21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('repost_id', sa.String(length=36), nullable=True))
    op.alter_column('posts', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('posts', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_foreign_key(None, 'posts', 'posts', ['repost_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.alter_column('posts', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('posts', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('posts', 'repost_id')
    # ### end Alembic commands ###
